<?xml version="1.0" encoding="UTF-8" ?>
<testsuites>
 <testsuite name="ApiTest1_apitest" package="assignment.suite" timestamp="2025-02-26 14:16:12.241 +0530"
 tests="1"  failures="1" errors="0" time="2.845000">
  <properties>
   <property name="RunDate" value="2025-02-26 14:16:12.241 +0530"/>
   <property name="Status" value="Failure"/>
  </properties>
  <testcase name="ApiTest1.apitest" assertions="1" status="failure"  time="2.845">
    <failure type="FAILURE" message="STMaxCallDepthExceeded: Handlers were called to a depth exceeding the maximum limit (40). HINT: One common cause for this error is a script that has been given the same name as a built-in command or function unintentionally calling itself. -- Execution Time 0:00:02 ApiTest1.apitest" />
  </testcase>
 </testsuite>
</testsuites>
